language: python

python:
  - 2.7

env:
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=packaging
  - TOX_ENV=style
  - TOX_ENV=docs
  - TOX_ENV=docs-linkcheck
  - TOX_ENV=docs-code-python27
  - TOX_ENV=docs-code-pypy
  - TOX_ENV=docs-code-python33
  - TOX_ENV=docs-code-python34

install:
  # Travis uses an outdated PyPy, this installs the most recent one.
  - "[[ ${TOX_ENV} == pypy ]] && sudo add-apt-repository -y ppa:pypy/ppa || true"
  - "[[ ${TOX_ENV} == pypy ]] && sudo apt-get -y update && sudo apt-get -y install pypy || true"
  - "[[ ${TOX_ENV} == pypy ]] && sudo rm -rf /usr/local/pypy/bin || true"
  - pip install --use-mirrors tox coveralls
  - pip install --editable .

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
