language: python

python:
  - 2.7

env:
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py33
  - TOX_ENV=packaging
  - TOX_ENV=style

install:
  # Travis uses an outdated PyPy, this installs the most recent one.
  - "[[ ${TOX_ENV} == pypy ]] && sudo add-apt-repository -y ppa:pypy/ppa || true"
  - "[[ ${TOX_ENV} == pypy ]] && sudo apt-get -y update && sudo apt-get -y install pypy || true"
  - "[[ ${TOX_ENV} == pypy ]] && sudo rm -rf /usr/local/pypy/bin || true"
  - pip install --use-mirrors tox
  - pip install --editable .

script:
  - tox -e $TOX_ENV
